### PR TITLE
remove out-of-line defns of constexpr static data members under c++17

### PR DESCRIPTION
**Pull request by yfeldblum**
Address warnings of this form under c++17 when building with `-Werror -Wdeprecated`:
```
fast_float/float_common.h:446:58: error: out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated [-Werror,-Wdeprecated]
constexpr double binary_format_lookup_tables<double, U>::powers_of_ten[];
                                                         ^
```

### CODE REVIEW

**Comment by lemire** [comment]
Looks reasonable. Let us run the tests.

**Comment by yfeldblum** [comment]
The formatting tests failed but, from the error messages, I didn't see how this is related to the PR. Is there something I need to do here?

**Comment by lemire** [comment]
@yfeldblum Looks fine. I will review and merge later.

**Comment by lemire** [comment]
Merging. This will part of the next release.

**Pull request merged**
