### PR TITLE
Extract the round to even loigic so it can be reused for hex floats.

### PR DESCRIPTION
**Pull request by deadalnix**
As a follow up to  #216 . It's not branchless, but, nevertheless, allow to extract part of the logic so it can be reused.

Running the benchmark shows no difference in term of instruction count, branch and whatnot with the previous code.

### CODE REVIEW

**Comment by lemire** [comment]
Merging. Will release shortly.

**Comment by deadalnix** [comment]
Thanks for looking into this. I did that quite some time ago. Can you point me where the algorithm changed? I want to consider if this is an error or something legit.

**Comment by lemire** [comment]
@deadalnix Among other things, you replaced `(product.low <= 1)` with `(product.low == 0)`. Several other things have been changed. We must validate each one of these changes.

**Comment by deadalnix** [comment]
Ha yes. I'll go over this again, why I did this is not 100% clear to me a year later.

**Comment by deadalnix** [comment]
I see what the transformation is.

The original code flows as follow:
```
if (!shouldRoundUp) {
  // Neutralize the rounding up.
}

// Round up if required.
```

The logic is changed as follow:
```
if (shouldRoundUp) {
  // Round up.
}

// Do nothing.
```

When flipping the condition, `(product.low <= 1)` becomes `(product.low > 1)` (and the `&&` becomes a `||`). So we are doing things differently when `product.low == 1`. However, in this case, we know the lower bits of the mantissa are going to be zero, so adding 1 or not won't change the end result after `answer.mantissa >>= 1`.

**Pull request merged**
