### PR TITLE
Fixes issue 47

### PR DESCRIPTION
**Pull request by lemire**
Fixes https://github.com/fastfloat/fast_float/issues/47

### CODE REVIEW

**Comment by aldanor** [comment]
Great, thanks!

**Comment by lemire** [comment]
Please keep reporting issues. :-)

**Comment by aldanor** [comment]
I'm trying to port the whole thing to Rust as an experiment, hence I'll probably read every single line of it and will report a few things later as a summary :)

**Comment by lemire** [comment]
@aldanor Email me at lemire@gmail.com if you'd like. I'm finishing the review of a paper I am about to post online. I'd also be interested in collaborating on a Rust port if you need the help. Note that we deliberately rely on (safe) integer overflow so you'll probably need `wrapping_` calls or something.

**Comment by aldanor** [comment]
Sounds good, I'll email you a link when it's more-or-less-done (and hopefully works), shouldn't take much longer. Yea, I've noticed reliance on unsigned overflows (so far mostly in `parse_number()`, let me know if there are any other particular parts of the code that also rely on that), already using wrapping ops there.

**Comment by lemire** [comment]
@aldanor I expect that the safe overflows are only at specific locations. Looking forward to taking your code out for a spin.

**Pull request merged**
