### PR TITLE
Constexpr from_chars

### PR DESCRIPTION
**Pull request by leni536**
Made `from_chars` constexpr when the following C++20 features are detected:
* `std::bit_cast`
* `std::is_constant_evaluated`
* constexpr algorithms

Added `FASTFLOAT_IS_CONSTEXPR` macro, for user code to detect if `from_chars` is constant expression. A more verbose `FASTFLOAT_FROM_CHARS_IS_CONSTEXPR` could make sense instead if there are plans to extend the library with unrelated non-constexpr floating point functionalities.

Added constexpr tests in the `verify` macro. It is disabled by default for now.

### CODE REVIEW

**Comment by leni536** [comment]
I had to swap fast_float.h and float_common.h in amalgamate.py, which I don't like, as it reduces readability of the amalgamated header file, as the public interface is no longer at the top.

Maybe I should put the `FASTFLOAT_CONSTEXPR20`  macro definition in the fast_float.h header instead.

**Comment by lemire** [comment]
@leni536 We can even add a new file if you'd like. No big deal.

**Comment by lemire** [comment]
Visual studio is complaining with 

fast_float\tests\basictest.cpp(828,3): error C2131: expression did not evaluate to a constant

**Comment by leni536** [comment]
> Visual studio is complaining with
> 
> fast_float\tests\basictest.cpp(828,3): error C2131: expression did not evaluate to a constant

Yes, I'm aware. I need to set up an MSVC toolchain to debug this, I don't have one ready.

Most of the errors are because of this trick to detect constexpr arguments not working in MSVC:
https://github.com/fastfloat/fast_float/pull/182/files#diff-2243980207b9a89b2b69852480cd08e4652a5ffe20d6be52dd1445d67dc0d542R637-R640

Except one is for this test:
https://github.com/fastfloat/fast_float/blob/264414c0b0760736561915dc54dfba6e9356c365/tests/basictest.cpp#L738

It compiles fine on clang 15 and gcc 12.

**Comment by lemire** [comment]
@leni536 Why is it so complicated... can't we just do something silly like this...

```C++
#include <cstring>

template<class T>
constexpr void to_digit(const char * b, const char *e, T& z) {
    z= e - b;
}

template<class T>
constexpr
bool basic_test(const char * data, T expected) {
  T actual;
  to_digit(data, data + strlen(data), actual);
  return expected == actual;
}

static_assert(basic_test("dsds", 4));
```

I mean, if the tests runs through a `static_assert`, then you know it was compile-time evaluated, right?

**Comment by leni536** [comment]
> @leni536 Why is it so complicated... can't we just do something silly like this...
> 
> ```c++
> #include <cstring>
> 
> template<class T>
> constexpr void to_digit(const char * b, const char *e, T& z) {
>     z= e - b;
> }
> 
> template<class T>
> constexpr
> bool basic_test(const char * data, T expected) {
>   T actual;
>   to_digit(data, data + strlen(data), actual);
>   return expected == actual;
> }
> 
> static_assert(basic_test("dsds", 4));
> ```
> 
> I mean, if the tests runs through a `static_assert`, then you know it was compile-time evaluated, right?

What complicates things are tests like `verify(some_runtime_expression, 4)`, which can never be evaluated at compile time if `some_runtime_expression` is also not usable at compile time. I wanted to automatically skip the compile-time testing for these tests. Alternatively I can have a separate `verify_constexpr` macro, that does compile time testing in addition to the runtime testing, and edit the bulk of the tests to use it (or have a `verify_runtime` or `verify_runtime_only` for the converse).

Anyway, maybe the `verify` macro could be simplified by using `basic_test` in the constexpr path as well, I might have overcomplicated that aspect.

**Comment by lemire** [comment]
@leni536 Building distinct tests for runtime and compile-time tests seems warranted. In a test harness, minimizing lines of code is not important.

**Comment by leni536** [comment]
Back to the drawing board.

In a new approach I converted `check_basic_test_result` to be usable for either runtime or constexpr checking.

This found an issue in clang 15, where `verify("-0", -0.0)` and `verify("-0", -0.0f)` fail at compile time on the sign check. gcc 12 compiles it fine. We will see what MSVC will do with it.

Output of clang 15:
```
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:730:3: error: constexpr variable 'verify_comptime_var' must be initialized by a constant expression
  verify("-0",-0.0);
  ^~~~~~~~~~~~~~~~~
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:689:5: note: expanded from macro 'verify'
    verify_comptime(lhs, rhs);                                                 \
    ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:675:19: note: expanded from macro 'verify_comptime'
    constexpr int verify_comptime_var =                                        \
                  ^
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:633:3: note: non-constexpr function 'error_not_equal' cannot be used in a constant expression
  FASTFLOAT_CHECK_EQ(copysign(1, actual), copysign(1, expected));
  ^
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:612:7: note: expanded from macro 'FASTFLOAT_CHECK_EQ'
      ComptimeDiag::error_not_equal();                                         \
      ^
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:644:3: note: in call to 'check_basic_test_result({2, &"-0"[0]}, {&"-0"[2], 0}, 0.000000e+00, -0.000000e+00)'
  check_basic_test_result<diag>(str, result, actual, expected);
  ^
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:730:3: note: in call to 'basic_test({2, &"-0"[0]}, -0.000000e+00)'
  verify("-0",-0.0);
  ^
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:689:5: note: expanded from macro 'verify'
    verify_comptime(lhs, rhs);                                                 \
    ^
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:676:10: note: expanded from macro 'verify_comptime'
        (basic_test<Diag::comptime>(lhs, rhs), 0);                             \
         ^
/home/lenard/git/github.com/fastfloat/fast_float/tests/basictest.cpp:602:19: note: declared here
      static void error_not_equal() {}
```

**Comment by leni536** [comment]
MSVC doesn't like this particular line:
https://github.com/leni536/fast_float/blob/6bd1e776b21415e5144d54a46234483896ca1905/tests/basictest.cpp#L781

Error message:
https://github.com/fastfloat/fast_float/actions/runs/4513362439/jobs/7948102809#step:4:252

But only when targeting x86. When targeting x64, it's fine.

**Comment by leni536** [comment]
> This is turning into a case study in using constexpr. :-)

It surely is. Now it looks like I finally fixed the VS17 C++20 builds.

In retrospect it makes sense that different code paths could be executed for x86 vs x64, the divergence is in bigint limb size.

I still have the clang issue remaining, now only reproduced locally. It would make sense to add constexpr checking CI workflows for recent gcc and clang compilers.

**Comment by lemire** [comment]
@leni536 Would that help: https://github.com/fastfloat/fast_float/pull/185

**Comment by leni536** [comment]
I think this PR is in a mergeable state now, constexpr tests now pass on the VS17 C++20 pipeline.

The constexpr tests are disabled by default and only enabled by setting the newly added `FASTFLOAT_CONSTEXPR_TESTS` cmake variable to true. This is relevant to #185.

Currently the constexpr tests only cover some happy path scenarios through the `verify` and `verify_options` macros. However as implemented, `from_chars` should be usable in constexpr when only part of the string gets parsed and even on parsing error. Cases like these are not covered yet.

**Comment by lemire** [comment]
Let us merge and update CI.

**Pull request merged**
