### PR TITLE
Testing changes and fixes

### PR DESCRIPTION
**Pull request by mumbleskates**
This moves tests with ~subsecond durations from the exhaustive test suite (which does not run in CI) to the default suite (which does). We also configure `long_test.cpp` (which was abandoned) to be in the default test suite and apply two fixes to it to make it compile and pass (`#include <iostream>` to make `std::cerr` etc. be defined, and apply the same whitespace-skipping fix we used in `string_test.cpp`).

### CODE REVIEW

**Comment by lemire** [comment]
This PR fails some of our tests.

**Comment by musicinmybrain** [comment]
Try adding `#include <string>` to `tests/string_test.cpp`. That should fix the CI failure. The absence of that include is a bug. Presumably nobody has ever tried to run that test on a platform where `iostream` doesn’t recursively include `string`.

**Comment by musicinmybrain** [comment]
There are some other headers that perhaps ought to be included to avoid making assumptions about recursive includes:

- `cstdio` for `std::snprintf`
- `limits` for `std::numeric_limits`
- `stdexcept` for `std::runtime_error` (technically, only in the not-msys/cygwin/sun case)
- `cctype` for `std::isspace`

**Comment by lemire** [comment]
@mumbleskates I am happy to merge now if you are happy with the PR.

**Comment by mumbleskates** [comment]
After some fiddling trying to understand what the CI was doing this looks like it should be fine. Feel free to merge!

**Comment by lemire** [comment]
Merging.

**Pull request merged**
