### PR TITLE
enum class chars_format

### LINKED ISSUE #278: Make fast_float::chars_format a scoped enumeration
Should fast_float::chars_format be changed into a scoped enumeration (`enum class`) to resemble std::chars_format?

I can do the work and PR, but I just wanted to check if you're okay with that change.

### PR DESCRIPTION
**Pull request by dalle**
Changed chars_format to an enum class.
Added operators to comply to [BitmaskType](https://en.cppreference.com/w/cpp/named_req/BitmaskType).

Fixes #278

### CODE REVIEW

**Comment by lemire** [comment]
@dalle What would you think about specifying `uint64_t` as the underlying type and casting to `uint64_t`? As the code currently stand, it would make no difference, but I tend to prefer fixed-size integers (for easier portability).

**Comment by dalle** [comment]
I'm all for it. uint32 or uint64?

**Comment by lemire** [comment]
> I'm all for it. uint32 or uint64?

I usually default on `uint64_t` in such cases.  Going for 32 bits saves nothing in this case.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
