### PR TITLE
from_chars_advanced overload function taking parsed_number_string_t

### PR DESCRIPTION
**Pull request by zejal**
Idea is to split parsing from value computation adding a from_chars_advanced function taking result of parsing.

### CODE REVIEW

**Comment by lemire** [comment]
@zejal Can you motivate this change? Why is it beneficial?

**Comment by zejal** [comment]
This would allow someone (as I would like to do to use fast_float in existing code) to write an alternative string parser function that creates and populates the parsed_number_string_t and call added overloaded function. Of course the existing from_chars_advanced taking chars range and parsing options remains and called suggested added one.

Perhaps accepting this change implies to document a bit what the contents of parsed_number_string_t structure. In particular the integer and fraction bits ?

**Comment by lemire** [comment]
> Perhaps accepting this change implies to document a bit what the contents of parsed_number_string_t structure. In particular the integer and fraction bits ?

Do you want to add some comments to the code so that this is clearer? No need to write very much, just enough so that people understand why the code is structured this way.

**Comment by zejal** [comment]
Thanks, added some comments, hope it helps.

**Comment by lemire** [comment]
I expect to merge once the test pass.

It should be part of the next release.

**Comment by zejal** [comment]
Sure, thanks a lot

**Pull request merged**
