### PR TITLE
This uses the template trick to ensure we get only one definition

### PR DESCRIPTION
**Pull request by lemire**
Should be self-explanatory.

Alternative to https://github.com/fastfloat/fast_float/pull/67

cc @wojdyr

### CODE REVIEW

**Comment by wojdyr** [comment]
Thanks a lot!

I tested it with various compiler options and linking fails with GCC in C++11/14

```
$ g++-9 -std=c++14 -g -O2 a.cpp b.cpp -Wall -W -I../include/usr/bin/ld: /tmp/cckD9eP6.o: in function `fast_float::adjusted_mantissa fast_float::compute_float<fast_float::binary_format<double> >(long, unsigned long)':
/home/wojdyr/fresh/fast_float/build/../include/fast_float/decimal_to_binary.h:80: undefined reference to `fast_float::powers_template<void>::power_of_five_128'
/usr/bin/ld: /tmp/cckD9eP6.o: in function `fast_float::value128 fast_float::compute_product_approximation<55>(long, unsigned long)':
/home/wojdyr/fresh/fast_float/build/../include/fast_float/decimal_to_binary.h:27: undefined reference to `fast_float::powers_template<void>::power_of_five_128'
/usr/bin/ld: /tmp/cckD9eP6.o: in function `fast_float::full_multiplication(unsigned long, unsigned long)':
/home/wojdyr/fresh/fast_float/build/../include/fast_float/float_common.h:157: undefined reference to `fast_float::powers_template<void>::power_of_five_128'
collect2: error: ld returned 1 exit status
```

I'll look into it again tomorrow.

**Comment by wojdyr** [comment]
Apparently it doesn't compile (GCC) with constexpr.

I'm using an older version of sajson where it works; I haven't realized that a few months ago this code was changed. Now it also doesn't compile for me.

Here is a small change that makes it similar to [this SO answer][1]. It compiles with recent GCC and Clang versions, I'll test it with other compilers this or next week.

```diff
--- a/include/fast_float/fast_table.h
+++ b/include/fast_float/fast_table.h
@@ -35,7 +35,11 @@ constexpr static int smallest_power_of_five = binary_format<double>::smallest_po
 constexpr static int largest_power_of_five = binary_format<double>::largest_power_of_ten();
 constexpr static int number_of_entries = 2 * (largest_power_of_five - smallest_power_of_five + 1);
 // Powers of five from 5^-342 all the way to 5^308 rounded toward one.
-constexpr static uint64_t power_of_five_128[number_of_entries] = {
+static const uint64_t power_of_five_128[number_of_entries];
+};
+
+template <class unused>
+const uint64_t powers_template<unused>::power_of_five_128[number_of_entries] = {
         0xeef453d6923bd65a,0x113faa2906a13b3f,
         0x9558b4661b6565f8,0x4ac7ca59a424c507,
         0xbaaee17fa23ebf76,0x5d79bcf00d2df649,
@@ -687,9 +691,9 @@ constexpr static uint64_t power_of_five_128[number_of_entries] = {
         0xb6472e511c81471d,0xe0133fe4adf8e952,
         0xe3d8f9e563a198e5,0x58180fddd97723a6,
         0x8e679c2f5e44ff8f,0x570f09eaa7ea7648,};
-};
+
 using powers = powers_template<>;
 
 }
 
-#endif
\ No newline at end of file
+#endif
```

[1]: https://stackoverflow.com/a/38043566/104453

**Comment by lemire** [comment]
@wojdyr Please check my latest commit.

Note that we build and test this code under GCC 7 and GCC 9 in CI. I'd like to know more about your setup where you have problems so we can reproduce them in CI.

I don't like to check code informally in such a manner. If there are problems, I want to be able to test for them.

**Comment by wojdyr** [comment]
It builds for me know.

Could you try if you can reproduce the previous problem with this:

    git checkout 2cbfc21
    g++ -std=c++11 tests/example_test.cpp -Iinclude

**Comment by lemire** [comment]
@wojdyr Ah. You are compiling with C++11.

See this PR:
https://github.com/fastfloat/fast_float/pull/69

**Comment by lemire** [comment]
Merging.

**Pull request merged**
