### PR TITLE
Round to even in a branchless fashion.

### PR DESCRIPTION
**Pull request by deadalnix**
As per title. There is no point risking a mispredict, especially since the branch condition is at least as complicated than the branchless version anyways.

### CODE REVIEW

**Comment by deadalnix** [comment]
Unfortunately, this doesn't seems to work. I'm failing to compile the benchmark with the following error:

```
[ 97%] Building CXX object benchmarks/CMakeFiles/benchmark.dir/benchmark.cpp.o
In file included from /home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/benchmark.cpp:25: /home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/dtoa.c:226: warning: "assert" redefined
  226 | #define assert(x) /*nothing*/
      |
In file included from /usr/include/c++/10/cassert:44,
                 from /home/deadalnix/repos/simple_fastfloat_benchmark/buildtest/_deps/doubleconversion-src/double-conversion/utils.h:34,
                 from /home/deadalnix/repos/simple_fastfloat_benchmark/buildtest/_deps/doubleconversion-src/double-conversion/diy-fp.h:31,
                 from /home/deadalnix/repos/simple_fastfloat_benchmark/buildtest/_deps/doubleconversion-src/double-conversion/ieee.h:31,
                 from /home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/benchmark.cpp:16: /usr/include/assert.h:50: note: this is the location of the previous definition
   50 | # define assert(expr)  (__ASSERT_VOID_CAST (0))
      |
/home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/benchmark.cpp: In instantiation of ‘double findmax_fastfloat(std::vector<std::__cxx11::basic_string<_CharT> >&) [with CharT = char16_t]’:
/home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/benchmark.cpp:359:106:   required from here
/home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/benchmark.cpp:183:42: error: no matching function for call to ‘from_chars(char16_t*, char16_t*, double&)’
  183 |     auto [p, ec] = fast_float::from_chars(st.data(), st.data() + st.size(), x);
      |                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/deadalnix/repos/simple_fastfloat_benchmark/buildtest/_deps/fast_float-src/include/fast_float/fast_float.h:62,
                 from /home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/benchmark.cpp:9:
/home/deadalnix/repos/simple_fastfloat_benchmark/buildtest/_deps/fast_float-src/include/fast_float/parse_number.h:66:19: note: candidate: ‘template<class T> fast_float::from_chars_result fast_float::from_chars(const char*, const char*, T&, fast_float::chars_format)’
   66 | from_chars_result from_chars(const char *first, const char *last,
      |                   ^~~~~~~~~~
/home/deadalnix/repos/simple_fastfloat_benchmark/buildtest/_deps/fast_float-src/include/fast_float/parse_number.h:66:19: note:   template argument deduction/substitution failed:
/home/deadalnix/repos/simple_fastfloat_benchmark/benchmarks/benchmark.cpp:183:50: note:   cannot convert ‘(& st)->std::__cxx11::basic_string<char16_t>::data()’ (type ‘char16_t*’) to type ‘const char*’
  183 |     auto [p, ec] = fast_float::from_chars(st.data(), st.data() + st.size(), x);
      |                                           ~~~~~~~^~
gmake[2]: *** [benchmarks/CMakeFiles/benchmark.dir/build.make:76: benchmarks/CMakeFiles/benchmark.dir/benchmark.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2721: benchmarks/CMakeFiles/benchmark.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by lemire** [comment]
> Unfortunately, this doesn't seems to work. I'm failing to compile the benchmark with the following error:

Is your branch up-to-date with https://github.com/fastfloat/fast_float? If not, please sync before doing any benchmarking.

**Comment by deadalnix** [comment]
Good catch, I was using lemire/fast_float , which is not up to date.

**Comment by deadalnix** [comment]
Running the benchmark numerous times, it's definitively within the noise.

**Comment by lemire** [comment]
Thanks.

I have added back a branch counter (some cloud systems do not support counting branches, so I had removed that). If you sync with [simple_fastfloat_benchmark](https://github.com/lemire/simple_fastfloat_benchmark) and execute in privileged mode, you should get the number of branches.

On an Intel Ice Lake server with GCC 11, I get the following... (the ` b/f` value is the average number of branch per float parsed).


```
fastfloat                               :   861.99 MB/s (+/- 2.1 %)    49.54 Mfloat/s      16.93 i/B   308.97 i/f (+/- 0.0 %)      3.53 c/B    64.34 c/f (+/- 2.1 %)      4.80 i/c     50.40 b/f      3.19 GHz 
```

After...

```
fastfloat                               :   812.23 MB/s (+/- 0.8 %)    46.68 Mfloat/s      17.48 i/B   319.00 i/f (+/- 0.0 %)      3.74 c/B    68.26 c/f (+/- 0.6 %)      4.67 i/c     49.49 b/f      3.19 GHz 
```

At a glance, on this system with this compiler and on this dataset, this PR saves a branch per float (so a 2% reduction in branching), at the cost of 10 extra instructions per float (so a 3% gain in instructions) which translates into about 4 extra cycles per float (so about 6% slower). It appears that the number of instructions per cycle is slightly reduced by the PR, maybe because there is a longer dependency chain.

**Comment by deadalnix** [comment]
I'm going to try to play around to see if that chain can be shortened. I'm not too worried about instruction count if there is a corresponding increase in ILP, but it doesn't looks like this is the case here. Time to try to shuffle things around and see how that goes.

**Comment by deadalnix** [comment]
I'm going to close this, as no matter how I shuffle things around, it doesn't seems to be possible to match the perf with branch and the branch is predictible enough so that mispredict are not a major concern.

**Pull request closed without merging**
